### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by andb0t** [Vorathel/Python_stuff#1]
Hi,
you have a syntax error in the import lines and below. Those lines:
```python
from tkinter import *
tkinter._test()
```
should read
```python
import tkinter as tk
tk._test()
```
Adapt the following lines accordingly. Your current version imports the tkinter namespace but not tkinter itself. That's why it fails. Abbreviating tkinter with tk is common practice, check out my git repo [here](https://github.com/andb0t/Fuxenpruefung/blob/31f8692dd3f5d587ebdf841d20dd517af7be78a6/src/fuxenpruefung.py).
Cheers!

**Comment by Vorathel** [comment]
My error is: 
cern@cern-VirtualBox:~/Desktop/python_programs$ python pytutorial2.pyTraceback (most recent call last):
  File "pytutorial2.py", line 2, in <module>
    import tkinter as tk
ImportError: No module named tkinter

**Comment by andb0t** [comment]
In this case you haven't installed tkinter correctly. How did you install tkinter?

**Comment by Vorathel** [comment]
sudo apt-get install python3-tk

**Comment by Vorathel** [comment]
Remind that I am using a VM. I hope this won't cause a problem.

**Comment by andb0t** [comment]
What is the result of `python --version` ?

**Comment by Vorathel** [comment]
`python -- version` -> Python 2.1.12
`python3 --version` -> Python 3.5.2

**Comment by andb0t** [comment]
Try `python3 pytutorial2.py`. Otherwise you use python 2, where you don't have tkinter installed.

**Comment by Vorathel** [comment]
Now it works:
`cern@cern-VirtualBox:~/Desktop/python_programs$ python3 -m py_compile pytutorial2.py
cern@cern-VirtualBox:~/Desktop/python_programs$ python3 pytutorial2.py`

Thanks for the support!
