### ISSUE TITLE
Remove temporary python files

### ISSUE THREAD

**Issue by andb0t** [Vorathel/Python_stuff#2]
Hi,
you have files ending with `.pyc` in your repo. Those are temporary files, where python stores the compiled code. They are recreated each time the code is executed and should not appear in a repo. To remove them you can
```shell
git rm *.pyc
git commit -m "Remove .pyc files"
```
Additionally, you have to tell git to ignore them from now on. You can steer that with a file named `.gitignore`. Just create a file with this name and write everything git should ignore in there, for example `*.pyc`. You can do both in one step by executing this:
```shell
echo '*.pyc' > .gitignore
git add .gitignore
git commit -m "Add .gitignore file"
git push
```
Cheers!

**Comment by Vorathel** [comment]
I added *.pyc to *gitignore. Thanks for mentioning.
